version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  algorithm:
    build: .
    depends_on:
      - ollama
    volumes:
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
      - ./entrypoint.sh:/algorithm/entrypoint.sh
    environment:
      DEV: "1"
      # TEST: "1"
      DIDS: '["sample_input"]'
      secret: "1234"
      TRANSFORMATION_DID: "1234"
      BASE_URL: "http://ollama:11434"

volumes:
  ollama-data: {}
