"""
This type stub file was generated by pyright.
"""

from dataclasses import InitVar, dataclass
from pathlib import Path
from typing import final
from oceanprotocol_job_details.ocean import DDO

@final
@dataclass(frozen=True)
class DDOLoader:
    ddo_paths: InitVar[list[Path]]
    _ddo_paths: list[Path] = ...
    def __post_init__(self, ddo_paths: list[Path]) -> None:
        ...
    
    def load(self) -> list[DDO]:
        ...
    


