"""
This type stub file was generated by pyright.
"""

from dataclasses import InitVar, dataclass
from pathlib import Path
from typing import Iterator, Sequence, final

@dataclass(frozen=True)
class DIDPaths:
    did: str
    ddo: Path
    input_files: Sequence[Path]
    def __post_init__(self) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    


@dataclass(frozen=True)
class Files:
    files: Sequence[DIDPaths]
    def __iter__(self) -> Iterator[DIDPaths]:
        ...
    
    def __len__(self) -> int:
        ...
    


@final
@dataclass(frozen=True)
class FilesLoader:
    dids: InitVar[str | None]
    transformation_did: InitVar[str | None]
    _dids: Sequence[str] = ...
    _transformation_did: str = ...
    def __post_init__(self, dids: str | None, transformation_did: str | None) -> None:
        ...
    
    def load(self) -> Files:
        ...
    


