"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Generic, Type, TypeVar, final
from oceanprotocol_job_details.ocean import JobDetails

T = TypeVar("T")
@final
@dataclass(frozen=True)
class JobDetailsLoader(Generic[T]):
    _type: Type[T] = ...
    def load(self) -> JobDetails[T]:
        ...
    


